# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  run_lint:
    docker:
    # Use the same Docker base as the project
    - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        # fallback to using the latest cache if no exact match is found.
        - v1-dependencies-

    - run:
        name: install dependencies1
        command: |
                  python3 -m venv devops
                  . devops/bin/activate
                  make install
                  # Install hadolint
                  wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                  chmod +x /bin/hadolint
    - save_cache:
        paths:
        - ./devops
        key: v1-dependencies-{{ checksum "requirements.txt" }}

    # run lint!
    - run:
        name: run lint
        command: |
                  . devops/bin/activate
                  make lint
upload_docker:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker:
      - run:
          name: Build and upload docker image to docker hub container
          command: |
            image="udacity-proj5-capstone-aj"
            docker build --tag=$image .
            docker image ls
            
            dockerpath="$DOCKER_USERNAME/$image"
            docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
            docker tag "$image" "${dockerpath}:${CIRCLE_WORKFLOW_ID:0:7}"
            docker tag "$image" "${dockerpath}:latest"
            docker push "${dockerpath}:${CIRCLE_WORKFLOW_ID:0:7}"
            docker push "${dockerpath}:latest"



workflows:
  version: 2.1
  default:
    jobs:
      - run_lint                  
