# Create Load balancer
apiVersion: v1
kind: Service
metadata:
  name: capstoneproject
spec:
  selector:
    app: ucapstoneproject
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
