# Create Load balancer
apiVersion: v1
kind: Service
metadata:
  name: udacity-proj5-capstone-aj
spec:
  selector:
    app: udacity-proj5-capstone-aj
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
