# Create Load balancer
apiVersion: v1
kind: Service
metadata:
  name: capstoneproject-svc
spec:
  selector:
    app: capstoneproject
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
