apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneproject
  namespace: default
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: capstoneproject
  template:
    metadata:
      labels:
        app: capstoneproject
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: capstoneproject
          image: jainsmailbox/udacity-proj5-capstone-aj:latest
          ports:
            - name: http
              containerPort: 5000
          imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
